### PR TITLE
Update to 0.5.1

### PR DESCRIPTION
**Pull request by dariocavada**
See change log:

## [0.5.1]
* Migration the example to null safety and to Android v2 embedding
* Update Android-Beacon-Library to version [2.19] with added support to Android 12 (https://github.com/AltBeacon/android-beacon-library/tree/2.19)
* Update README.md with new Android permission requirement for location (SDK 29+, Android 10, 11)

### CODE REVIEW

**Comment by alann-maulana** [comment]
Thanks @dariocavada 

Will wait for the workflows done running.

**Comment by alann-maulana** [comment]
@dariocavada  Can you fix the analyzer issues by running `flutter analyze .`

**Comment by dariocavada** [comment]
fixed analyzer issue

**Comment by alann-maulana** [comment]
Thanks @dariocavada

**Pull request merged**
