### PR TITLE
Add customizable scan time period on Android. Closes #76

### LINKED ISSUE #76: Allow to customize scan period on Android
Hi! Thanks for your work.
AltBeacon, on which this plugin is based on for the Android part, allows developers to customize the duration of the bluetooth scan period.

This is done with the method `setForegroundScanPeriod(long p)`

It would be nice to expose this optional settings to the Flutter side, so the plugin could support more uses cases.

### PR DESCRIPTION
**Pull request by paolorotolo**
This PR adds the ability for developer to set a custom scan time for the Android beacon scanner.

For example, using:
```
    await flutterBeacon.setAndroidScanPeriod(300);
```

will fire the ranging callback every 300ms instead of the default AltBeacon library value.

### CODE REVIEW

**Comment by paolorotolo** [comment]
Also added another method `await flutterBeacon.setAndroidBetweenScanPeriod(300)` to set time between scans.

**Comment by paolorotolo** [comment]
Synced the pull with upstream and triggered tests again.

**Comment by alann-maulana** [comment]
Hi @paolorotolo 

- Some build failed, please check using `make reformatting`
- There is no test case for new added function, so coverage report failed too
- We will make this little library as general as possible, just use `setScanPeriod ` and `setBetweenScanPeriod ` name. And make "empty-function" on iOS. This will make both function called on both Android and iOS, but this will "do-nothing" on iOS. You can check how to handle `openBluetoothSettings` function at iOS at https://github.com/alann-maulana/flutter_beacon/blob/master/ios/Classes/FlutterBeaconPlugin.m#L177

**Comment by paolorotolo** [comment]
Sure, there you go 👍🏻

**Comment by alann-maulana** [comment]
Oops, failed to send coverage test report on coveralls. again! 

BTW Thanks @paolorotolo

**Comment by alann-maulana** [comment]
This is weird, only by enable verbose mode on coveralls report. It is running well without trouble 0481084674536ae52dc50059adf3151eeeb6970f  - https://github.com/alann-maulana/flutter_beacon/runs/2517400944?check_suite_focus=true

Can you please pull from master again @paolorotolo 
Thanks

**Comment by paolorotolo** [comment]
@alann-maulana sure, just rebased

**Comment by alann-maulana** [comment]
Thanks @paolorotolo

**Pull request merged**
